### PR TITLE
Update WCOSS2 to spack-stack 1.9 to fix build error

### LINKED ISSUE #453: [bug] RDASApp cannot build on WCOSS2 after updating submodules in #441
## Current behavior (describe the bug)

Checking out the develop branch of RDASApp and building on WCOSS2 leads to this error around 43%: 

```
/lfs/h2/emc/da/noscrub/samuel.degelia/RDASApp_checkfv3build/RDASApp/bundle/oops/src/test/util/ParallelFieldSetIO.cc(11): catastrophic error: cannot open source file "filesystem"
  #include <filesystem>
                       ^

compilation aborted for /lfs/h2/emc/da/noscrub/samuel.degelia/RDASApp_checkfv3build/RDASApp/bundle/oops/src/test/util/ParallelFieldSetIO.cc (code 4)
make[2]: *** [oops/src/CMakeFiles/test_util_parallelfieldsetio_1PE.dir/build.make:76: oops/src/CMakeFiles/test_util_parallelfieldsetio_1PE.dir/test/util/ParallelFieldSetIO.cc.o] Error 4
make[2]: Leaving directory '/lfs/h2/emc/da/noscrub/samuel.degelia/RDASApp_checkfv3build/RDASApp/build'
make[1]: *** [CMakeFiles/Makefile2:8845: oops/src/CMakeFiles/test_util_parallelfieldsetio_1PE.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/lfs/h2/emc/da/noscrub/samuel.degelia/RDASApp_checkfv3build/RDASApp/build'
```

This error did not occur before updating the submodules in #441. 

The error can be resolved by building with spack-stack 1.9.2. I will check that the ctests still pass after updating and then open a PR to resolve this.

### PR DESCRIPTION
**Pull request by SamuelDegelia-NOAA**
## Description
After updating the submodules in #441, RDASApp fails to build on WCOSS2. This can be resolved by updating to spack-stack 1.9. The new modulefile for spack-stack 1.9 is taken from GDASApp. 

There is an additional change here to update the wrapper script for running ctests on WCOSS2. We need to prepend `${RDASApp}/build/lib` and `${RDASApp}/build/lib64` to our `LD_LIBRARY_PATH` to prevent a system `libesmf.so` from taking precedence over the ESMF built with RDASApp. 

After this change, RDASApp can now build on WCOSS2 and all ctests are passing. 

Side note: we should probably try and get some CI testing set up on WCOSS2 to catch issues like this in the future. 

## Issue(s) addressed
Closes #453

## Dependencies (if applicable)
None

## Checklist
- [x] I have performed a self-review of my own code.
- [x] I have run rrfs tests before creating the PR (if applicable).

### CODE REVIEW

**Comment by SamuelDegelia-NOAA** [comment]
```
+ ctest -j8
Test project /lfs/h2/emc/da/noscrub/samuel.degelia/RDASApp_debug/RDASApp/build/rrfs-test
    Start 2: rrfs_fv3jedi_2024052700_getkf_observer
    Start 6: rrfs_mpasjedi_2024052700_getkf_observer
    Start 1: rrfs_fv3jedi_2024052700_Ens3Dvar
    Start 4: rrfs_mpasjedi_2024052700_bumploc
    Start 5: rrfs_mpasjedi_2024052700_Ens3Dvar
    Start 8: rrfs_bufr2ioda_msonet
1/8 Test #8: rrfs_bufr2ioda_msonet .....................   Passed   37.07 sec
2/8 Test #4: rrfs_mpasjedi_2024052700_bumploc ..........   Passed  477.68 sec
3/8 Test #6: rrfs_mpasjedi_2024052700_getkf_observer ...   Passed  589.69 sec
    Start 7: rrfs_mpasjedi_2024052700_getkf_solver
4/8 Test #2: rrfs_fv3jedi_2024052700_getkf_observer ....   Passed  593.57 sec
    Start 3: rrfs_fv3jedi_2024052700_getkf_solver
5/8 Test #1: rrfs_fv3jedi_2024052700_Ens3Dvar ..........   Passed  616.56 sec
6/8 Test #5: rrfs_mpasjedi_2024052700_Ens3Dvar .........   Passed  634.54 sec
7/8 Test #3: rrfs_fv3jedi_2024052700_getkf_solver ......   Passed  353.03 sec
8/8 Test #7: rrfs_mpasjedi_2024052700_getkf_solver .....   Passed  459.88 sec

100% tests passed, 0 tests failed out of 8

Label Time Summary:
rdas-bundle    = 3762.01 sec*proc (8 tests)
script         = 3762.01 sec*proc (8 tests)

Total Test time (real) = 1049.62 sec
+ exit 0
```

File: rrfs-test/ush/wrapper_ctest_pbs.sh [hunk 1]
```diff
@@ -31,7 +31,7 @@ ulimit -v unlimited
 ulimit -a
 export OOPS_TRACE=0
 export OMP_NUM_THREADS=1
-export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${RDASApp}/build/lib"
+export LD_LIBRARY_PATH="${RDASApp}/build/lib64:${RDASApp}/build/lib:${LD_LIBRARY_PATH}"
```
Comment (guoqing-noaa) [inline rrfs-test/ush/wrapper_ctest_pbs.sh]: `lib64` is a link to `lib`,
I think, similar to what we did in rrfs-workflow, using `lib64` only (ie. without `lib`) may be enough.

https://github.com/NOAA-EMC/rrfs-workflow/blob/rrfs-mpas-jedi/workflow/sideload/launch.sh#L69

**Review by TingLei-NOAA — DISMISSED** [review]
Thanks for this update!

File: rrfs-test/ush/wrapper_ctest_pbs.sh (hunk 1 above)
Comment (SamuelDegelia-NOAA) [reply rrfs-test/ush/wrapper_ctest_pbs.sh]: Thanks @guoqing-noaa, just removed the `lib` portion. The important change here is prepending instead of appending to `${LD_LIBRARY_PATH}` which is needed to prevent conflicts with `libesmf.so`.

**Review by TingLei-NOAA — APPROVED** [review]

**Review by ShunLiu-NOAA — APPROVED** [review]

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA This is a good case demonstrating that we should alway prepend our own library instead of append to `LD_LIBRARY_PATH `.  This will also solve our current GSIBEC issue (i.e. we don't need to unload gsibec, instead we can prepend RDASApp library so that mpasjedi uses the newly built GSIBEC in RDASApp instead of the spack-stack GSIBEC.
